title: Qt Virtual machines manager
description: qt virtual machine manager libvirt spice vnc lxc kvm qemu xen openvz vbox vmware hyperv powervm bhyve
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  
meta:
  - name: ocs-site-verification
  - content: ba9d219365f62cbdadc0b356f1be1252
